### PR TITLE
Fix clang 13 errors when using pedantic

### PR DESCRIPTION
**Pull request by fran6co**

### CODE REVIEW

**Comment by fran6co** [comment]
Hi, we do. We could separate the flags for Harfang and keep them as warnings but I thought they were some fair changes to send upstream. Specially the `PipelineResources` sometimes forward declared as a struct and sometimes as a class

**Comment by fran6co** [comment]
I can remove the `[[maybe_unused]]` commit from this PR if it's something that you wouldn't like in the codebase. For now it's the only place  clang complains about but more might pop up

**Comment by harfang3dadmin** [comment]
Ok!
What is surprising is that the pedantic mode should raise a lot more warnings, especially on the externs.
Would you mind sharing the details of your toolchain (OS family, compiler, invocation command line) ?
It would help us to figure out what is the nature of the issue on the struct/class inconsistency.

Regarding `[[maybe_unused]]`, it would indeed require C++17 to build HARFANG, where only C++14 is needed as of today. For this reason, we would rather not apply this change.

**Comment by fran6co** [comment]
Just remove the `[[maybe_unused]]` commit. I thought we were using pedantic but we are not, this are the flags for clang:

```
-std=c++17 -Wall -Wextra -Werror -Wno-unknown-pragmas -Wno-unused-but-set-variable -Wmaybe-uninitialized -Wno-unknown-warning-option
```

**Pull request closed without merging**
